FROM golang:1.20

WORKDIR /app

RUN apt-get update && apt-get -y install default-mysql-client

RUN go install github.com/kyoh86/richgo@latest && \
  go install bitbucket.org/liamstask/goose/cmd/goose@latest

RUN go install github.com/makiuchi-d/arelo@latest

ENTRYPOINT ["sh", "./entrypoint.sh"]
