version: "2"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - PORT=8080
      - GO_ENV=development
      - DB_USER=root
      - DB_NAME=user
      - DB_PASSWORD=
      - TEST_DB_NAME=user_test
      - DB_HOST=db
      - DB_PORT=3306
    command: "go run main.go"
    volumes:
      - ./:/go/src
    working_dir: /go/src
    ports:
      - "8080:8080"
    links:
      - db
  db:
    build:
      context: ./mysql/docker
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/volume:/var/lib/mysql:delegated
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    platform: linux/x86_64

volumes:
  db-data:
